// Starter taxonomy, identical to supabase/migrations/0017. The admin "Load
// starter data" button inserts it through the normal RLS-checked client, so a
// fresh database can be filled without opening the SQL editor.

export const STARTER_COUNTRY = {
  slug: 'pakistan',
  name: 'Pakistan',
  iso2: 'PK',
  latitude: 30.3753,
  longitude: 69.3451,
};

export const STARTER_REGIONS: { slug: string; name: string; lat: number; lng: number }[] = [
  { slug: 'punjab', name: 'Punjab', lat: 31.1704, lng: 72.7097 },
  { slug: 'sindh', name: 'Sindh', lat: 25.8943, lng: 68.5247 },
  { slug: 'khyber-pakhtunkhwa', name: 'Khyber Pakhtunkhwa', lat: 34.9526, lng: 72.3311 },
  { slug: 'balochistan', name: 'Balochistan', lat: 28.4907, lng: 65.0958 },
  {
    slug: 'islamabad-capital-territory',
    name: 'Islamabad Capital Territory',
    lat: 33.7205,
    lng: 73.0405,
  },
  { slug: 'gilgit-baltistan', name: 'Gilgit-Baltistan', lat: 35.8026, lng: 74.9832 },
  { slug: 'azad-kashmir', name: 'Azad Jammu and Kashmir', lat: 33.9259, lng: 73.781 },
];

export const STARTER_CITIES: {
  region: string;
  slug: string;
  name: string;
  lat: number;
  lng: number;
  featured: boolean;
}[] = [
  { region: 'punjab', slug: 'lahore', name: 'Lahore', lat: 31.5204, lng: 74.3587, featured: true },
  {
    region: 'punjab',
    slug: 'faisalabad',
    name: 'Faisalabad',
    lat: 31.4504,
    lng: 73.135,
    featured: true,
  },
  {
    region: 'punjab',
    slug: 'rawalpindi',
    name: 'Rawalpindi',
    lat: 33.5651,
    lng: 73.0169,
    featured: true,
  },
  { region: 'punjab', slug: 'multan', name: 'Multan', lat: 30.1575, lng: 71.5249, featured: true },
  {
    region: 'punjab',
    slug: 'gujranwala',
    name: 'Gujranwala',
    lat: 32.1877,
    lng: 74.1945,
    featured: false,
  },
  {
    region: 'punjab',
    slug: 'sialkot',
    name: 'Sialkot',
    lat: 32.4945,
    lng: 74.5229,
    featured: false,
  },
  {
    region: 'punjab',
    slug: 'bahawalpur',
    name: 'Bahawalpur',
    lat: 29.3544,
    lng: 71.6911,
    featured: false,
  },
  {
    region: 'punjab',
    slug: 'sargodha',
    name: 'Sargodha',
    lat: 32.074,
    lng: 72.6861,
    featured: false,
  },
  {
    region: 'punjab',
    slug: 'sheikhupura',
    name: 'Sheikhupura',
    lat: 31.7167,
    lng: 73.985,
    featured: false,
  },
  { region: 'punjab', slug: 'gujrat', name: 'Gujrat', lat: 32.5731, lng: 74.1005, featured: false },
  {
    region: 'punjab',
    slug: 'sahiwal',
    name: 'Sahiwal',
    lat: 30.6682,
    lng: 73.1114,
    featured: false,
  },
  {
    region: 'punjab',
    slug: 'rahim-yar-khan',
    name: 'Rahim Yar Khan',
    lat: 28.4202,
    lng: 70.2952,
    featured: false,
  },
  { region: 'sindh', slug: 'karachi', name: 'Karachi', lat: 24.8607, lng: 67.0011, featured: true },
  {
    region: 'sindh',
    slug: 'hyderabad',
    name: 'Hyderabad',
    lat: 25.396,
    lng: 68.3578,
    featured: false,
  },
  { region: 'sindh', slug: 'sukkur', name: 'Sukkur', lat: 27.7052, lng: 68.8574, featured: false },
  { region: 'sindh', slug: 'larkana', name: 'Larkana', lat: 27.557, lng: 68.2264, featured: false },
  {
    region: 'sindh',
    slug: 'nawabshah',
    name: 'Nawabshah',
    lat: 26.2442,
    lng: 68.41,
    featured: false,
  },
  {
    region: 'khyber-pakhtunkhwa',
    slug: 'peshawar',
    name: 'Peshawar',
    lat: 34.0151,
    lng: 71.5249,
    featured: true,
  },
  {
    region: 'khyber-pakhtunkhwa',
    slug: 'mardan',
    name: 'Mardan',
    lat: 34.1989,
    lng: 72.0231,
    featured: false,
  },
  {
    region: 'khyber-pakhtunkhwa',
    slug: 'abbottabad',
    name: 'Abbottabad',
    lat: 34.1688,
    lng: 73.2215,
    featured: false,
  },
  {
    region: 'khyber-pakhtunkhwa',
    slug: 'mingora',
    name: 'Mingora (Swat)',
    lat: 34.7717,
    lng: 72.36,
    featured: false,
  },
  {
    region: 'khyber-pakhtunkhwa',
    slug: 'dera-ismail-khan',
    name: 'Dera Ismail Khan',
    lat: 31.8314,
    lng: 70.9019,
    featured: false,
  },
  {
    region: 'balochistan',
    slug: 'quetta',
    name: 'Quetta',
    lat: 30.1798,
    lng: 66.975,
    featured: true,
  },
  {
    region: 'balochistan',
    slug: 'gwadar',
    name: 'Gwadar',
    lat: 25.1264,
    lng: 62.3225,
    featured: false,
  },
  {
    region: 'islamabad-capital-territory',
    slug: 'islamabad',
    name: 'Islamabad',
    lat: 33.6844,
    lng: 73.0479,
    featured: true,
  },
  {
    region: 'gilgit-baltistan',
    slug: 'gilgit',
    name: 'Gilgit',
    lat: 35.9208,
    lng: 74.308,
    featured: false,
  },
  {
    region: 'azad-kashmir',
    slug: 'muzaffarabad',
    name: 'Muzaffarabad',
    lat: 34.37,
    lng: 73.4711,
    featured: false,
  },
];

export const STARTER_CATEGORIES: {
  slug: string;
  name: string;
  description: string;
  sort_order: number;
  is_featured: boolean;
}[] = [
  {
    slug: 'restaurants',
    name: 'Restaurants',
    description: 'Restaurants, cafes, bakeries and takeaways.',
    sort_order: 10,
    is_featured: true,
  },
  {
    slug: 'doctors',
    name: 'Doctors & Clinics',
    description: 'General physicians, specialists and clinics.',
    sort_order: 20,
    is_featured: true,
  },
  {
    slug: 'dentists',
    name: 'Dentists',
    description: 'Dental clinics and orthodontists.',
    sort_order: 30,
    is_featured: true,
  },
  {
    slug: 'hospitals',
    name: 'Hospitals',
    description: 'Hospitals, labs and diagnostic centres.',
    sort_order: 40,
    is_featured: false,
  },
  {
    slug: 'pharmacies',
    name: 'Pharmacies',
    description: 'Chemists and medical stores.',
    sort_order: 50,
    is_featured: false,
  },
  {
    slug: 'beauty-salons',
    name: 'Beauty Salons & Spas',
    description: 'Salons, barbers, spas and bridal makeup.',
    sort_order: 60,
    is_featured: true,
  },
  {
    slug: 'gyms',
    name: 'Gyms & Fitness',
    description: 'Gyms, fitness studios and trainers.',
    sort_order: 70,
    is_featured: false,
  },
  {
    slug: 'schools',
    name: 'Schools & Academies',
    description: 'Schools, tuition centres and training institutes.',
    sort_order: 80,
    is_featured: true,
  },
  {
    slug: 'real-estate',
    name: 'Real Estate',
    description: 'Property dealers, builders and developers.',
    sort_order: 90,
    is_featured: true,
  },
  {
    slug: 'car-repair',
    name: 'Car Repair',
    description: 'Mechanics, workshops, tyres and car wash.',
    sort_order: 100,
    is_featured: false,
  },
  {
    slug: 'car-dealers',
    name: 'Car Dealers',
    description: 'New and used car showrooms and rentals.',
    sort_order: 110,
    is_featured: false,
  },
  {
    slug: 'plumbers',
    name: 'Plumbers',
    description: 'Plumbing, water tanks and sanitary work.',
    sort_order: 120,
    is_featured: true,
  },
  {
    slug: 'electricians',
    name: 'Electricians',
    description: 'Electrical repair, wiring, solar and UPS.',
    sort_order: 130,
    is_featured: true,
  },
  {
    slug: 'ac-repair',
    name: 'AC & Appliance Repair',
    description: 'Air conditioner, fridge and appliance servicing.',
    sort_order: 140,
    is_featured: false,
  },
  {
    slug: 'lawyers',
    name: 'Lawyers',
    description: 'Law firms, advocates and legal consultants.',
    sort_order: 150,
    is_featured: false,
  },
  {
    slug: 'accountants',
    name: 'Accountants & Tax',
    description: 'Accountants, tax consultants and auditors.',
    sort_order: 160,
    is_featured: false,
  },
  {
    slug: 'hotels',
    name: 'Hotels & Guest Houses',
    description: 'Hotels, guest houses and short stays.',
    sort_order: 170,
    is_featured: false,
  },
  {
    slug: 'travel-agents',
    name: 'Travel Agents',
    description: 'Travel, tickets, visas, Hajj and Umrah.',
    sort_order: 180,
    is_featured: false,
  },
  {
    slug: 'shopping',
    name: 'Shopping & Retail',
    description: 'Shops, supermarkets, clothing and electronics.',
    sort_order: 190,
    is_featured: false,
  },
  {
    slug: 'it-services',
    name: 'IT & Web Services',
    description: 'Software houses, web design, repair and internet.',
    sort_order: 200,
    is_featured: false,
  },
  {
    slug: 'event-services',
    name: 'Events & Wedding',
    description: 'Marquees, caterers, photographers and decorators.',
    sort_order: 210,
    is_featured: false,
  },
  {
    slug: 'home-services',
    name: 'Home Services',
    description: 'Cleaning, pest control, movers and carpenters.',
    sort_order: 220,
    is_featured: false,
  },
];
